# Generated by Django 3.2.6 on 2021-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_text_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'wykonawca',
                'verbose_name_plural': 'wykonawcy',
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='musician',
            field=models.ManyToManyField(related_name='music', to='music.Musician', verbose_name='wykonawcy'),
        ),
    ]
