# Generated by Django 3.2.6 on 2021-08-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musician',
            name='about',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musician',
            field=models.ManyToManyField(related_name='songs', to='music.Musician', verbose_name='wykonawcy'),
        ),
        migrations.AlterField(
            model_name='song',
            name='published_at',
            field=models.DateField(verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='song',
            name='short_description',
            field=models.TextField(verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='song',
            name='text_link',
            field=models.CharField(default='No link', max_length=150, verbose_name='link do tekstu'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
    ]
