# Generated by Django 3.2.6 on 2021-08-30 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_auto_20210830_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'piosenka', 'verbose_name_plural': 'piosenki'},
        ),
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='auth.user'),
            preserve_default=False,
        ),
    ]
