# Generated by Django 3.2.6 on 2021-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_song_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='data publikacji'),
        ),
    ]
