# Generated by Django 3.2.6 on 2021-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_remove_song_audio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(blank=True, default='No link', max_length=200, null=True, verbose_name='link do YouTube'),
        ),
    ]
